query getOrderById($id: Int!) {
  order(id: $id) {
    id
    userId
    createdAt
    updatedAt
    firstName
    lastName
    streetAddress
    postalCode
    email
    phoneNumber
    products {
      productId
      name
      description
      unit
      price
      quantity
    }
  }
}
